api_login_check:
    path: /api/login_check

fos_user_registration_confirm:
    controller: App\Controller\Api\UserController::confirmAction
    path: /register/confirm
    methods: GET

fos_user_registration_register:
    controller: App\Controller\Api\UserController::registerAction
    path: /register
    methods: POST

fos_user_resetting_send_email:
    controller: App\Controller\Api\UserController::requestResetPasswordAction
    path: /password/request
    methods: POST

fos_user_resetting_reset:
    controller: App\Controller\Api\UserController::resetPasswordAction
    path: /password/reset
    methods: POST

fos_user_profile_edit:
    controller: App\Controller\Api\UserController::editProfileAction
    path: /me/settings
    methods: PATCH

api.user_search:
    controller: App\Controller\Api\UserController::searchAction
    path: /users/search
    methods: GET

api.user_find:
    controller: App\Controller\Api\UserController::findAction
    path: /users/find
    methods: GET

api.login_request:
    controller: App\Controller\Api\UserController::magicLinkRequestAction
    path: /auth/request
    methods: POST

api.mlink_redir:
    controller: App\Controller\Api\UserController::magicLinkRedirect
    path: /mlink/{mlinkHash}
    methods: GET

api.user.cheer:
    controller: App\Controller\Api\UserController::addCheer
    path: /users/{userId}/cheer
    methods: POST

api.data:
    controller: App\Controller\Api\UserController::getAll
    path: /data/aggregate
    methods: GET